name: Deploy to Firebase on Push

on:
  push:
    branches:
      - main
      - master

permissions:
  contents: read

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true  # อัปเดตตามระบบ GitHub 2026

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18  # ตัวระบบ Firebase Functions ยังคงต้องการ Node.js 18 ในการรันหลังบ้าน
          cache: 'npm'
          cache-dependency-path: functions/package.json

      - name: Install Functions Dependencies
        run: |
          cd functions
          npm install

      - name: Deploy to Firebase Hosting & Functions
        uses: w9jds/firebase-action@master
        with:
          args: deploy
        env:
          GCP_SA_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
